<?php

namespace PS\ParametreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassRepository extends EntityRepository
{
    public function findSearch($nom)
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->where("a.identifiant LIKE :nom")
            ->orderBy('a.identifiant', 'ASC')
            ->setParameter('nom', '%' . $nom . '%');

        return $qb->getQuery()->getResult();

    }

}
