parameters:
#    parametre.example.class: SM\ParametreBundle\Example

services:
#    parametre.example:
#        class: %parametre.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
