imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ParametreBundle/Resources/config/services.yml" }
    - { resource: "@UtilisateurBundle/Resources/config/services.yml" }
    - { resource: "@GestionBundle/Resources/config/services.yml" }
    - { resource: "@SiteBundle/Resources/config/services.yml" }
    - { resource: "@PSApiBundle/Resources/config/services.yml" }
    - { resource: "@MobileBundle/Resources/config/services.yml" }
    #- { resource: "@PSSpecialiteBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    upload_dir: '%kernel.root_dir%/../web/uploads'
    signature_dir: '%kernel.root_dir%/../data'
    data_dir: '%signature_dir%'
    bundle_dir: '%kernel.root_dir%/../web'
    bizao_access_token: bktoT1pYUlVrOWJFcDJ6U0lQX1JDNEVRNEY0YTpwU1BkeGJDcEJlNUVPUTFVa1ZGeHo3RERIYUlh
    bizao_client_id: nKhOZXRUk9bEp2zSIP_RC4EQ4F4a
    bizao_client_secret:  pSPdxbCpBe5EOQ1UkVFxz7DDHaIa
    bizao_host: https://api.bizao.com
    bizao_uri: /omoneypay/v1

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    assets:
        version: 'v3'
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
      admin_skin: '%admin_skin%'
    #form_themes:
            #- 'TetranzSelect2EntityBundle:Form:fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
             datetime_functions:
                 convert_tz: DoctrineExtensions\Query\Mysql\ConvertTz
                 date: DoctrineExtensions\Query\Mysql\Date
                 date_format: DoctrineExtensions\Query\Mysql\DateFormat
                 dateadd: DoctrineExtensions\Query\Mysql\DateAdd
                 datesub: DoctrineExtensions\Query\Mysql\DateSub
                 datediff: DoctrineExtensions\Query\Mysql\DateDiff
                 day: DoctrineExtensions\Query\Mysql\Day
                 dayname: DoctrineExtensions\Query\Mysql\DayName
                 dayofweek: DoctrineExtensions\Query\Mysql\DayOfWeek
                 dayofyear: DoctrineExtensions\Query\Mysql\DayOfYear
                 div: DoctrineExtensions\Query\Mysql\Div
                 from_unixtime: DoctrineExtensions\Query\Mysql\FromUnixtime
                 hour: DoctrineExtensions\Query\Mysql\Hour
                 last_day: DoctrineExtensions\Query\Mysql\LastDay
                 minute: DoctrineExtensions\Query\Mysql\Minute
                 now: DoctrineExtensions\Query\Mysql\Now
                 month: DoctrineExtensions\Query\Mysql\Month
                 monthname: DoctrineExtensions\Query\Mysql\MonthName
                 second: DoctrineExtensions\Query\Mysql\Second
                 sectotime: DoctrineExtensions\Query\Mysql\SecToTime
                 strtodate: DoctrineExtensions\Query\Mysql\StrToDate
                 time: DoctrineExtensions\Query\Mysql\Time
                 timediff: DoctrineExtensions\Query\Mysql\TimeDiff
                 timestampadd: DoctrineExtensions\Query\Mysql\TimestampAdd
                 timestampdiff: DoctrineExtensions\Query\Mysql\TimestampDiff
                 timetosec: DoctrineExtensions\Query\Mysql\TimeToSec
                 week: DoctrineExtensions\Query\Mysql\Week
                 weekday: DoctrineExtensions\Query\Mysql\WeekDay
                 year: DoctrineExtensions\Query\Mysql\Year
                 yearmonth: DoctrineExtensions\Query\Mysql\YearMonth
                 yearweek: DoctrineExtensions\Query\Mysql\YearWeek
                 unix_timestamp: DoctrineExtensions\Query\Mysql\UnixTimestamp
                 utc_timestamp: DoctrineExtensions\Query\Mysql\UtcTimestamp
                 extract: DoctrineExtensions\Query\Mysql\Extract

             numeric_functions:
                 acos: DoctrineExtensions\Query\Mysql\Acos
                 asin: DoctrineExtensions\Query\Mysql\Asin
                 atan2: DoctrineExtensions\Query\Mysql\Atan2
                 atan: DoctrineExtensions\Query\Mysql\Atan
                 bit_count: DoctrineExtensions\Query\Mysql\BitCount
                 bit_xor: DoctrineExtensions\Query\Mysql\BitXor
                 ceil: DoctrineExtensions\Query\Mysql\Ceil
                 cos: DoctrineExtensions\Query\Mysql\Cos
                 cot: DoctrineExtensions\Query\Mysql\Cot
                 degrees: DoctrineExtensions\Query\Mysql\Degrees
                 exp: DoctrineExtensions\Query\Mysql\Exp
                 floor: DoctrineExtensions\Query\Mysql\Floor
                 log: DoctrineExtensions\Query\Mysql\Log
                 log10: DoctrineExtensions\Query\Mysql\Log10
                 log2: DoctrineExtensions\Query\Mysql\Log2
                 pi: DoctrineExtensions\Query\Mysql\Pi
                 power: DoctrineExtensions\Query\Mysql\Power
                 quarter: DoctrineExtensions\Query\Mysql\Quarter
                 radians: DoctrineExtensions\Query\Mysql\Radians
                 rand: DoctrineExtensions\Query\Mysql\Rand
                 round: DoctrineExtensions\Query\Mysql\Round
                 stddev: DoctrineExtensions\Query\Mysql\StdDev
                 sin: DoctrineExtensions\Query\Mysql\Sin
                 std: DoctrineExtensions\Query\Mysql\Std
                 tan: DoctrineExtensions\Query\Mysql\Tan
                 variance: DoctrineExtensions\Query\Mysql\Variance

             string_functions:
                 aes_decrypt: DoctrineExtensions\Query\Mysql\AesDecrypt
                 aes_encrypt: DoctrineExtensions\Query\Mysql\AesEncrypt
                 any_value: DoctrineExtensions\Query\Mysql\AnyValue
                 ascii: DoctrineExtensions\Query\Mysql\Ascii
                 binary: DoctrineExtensions\Query\Mysql\Binary
                 char_length: DoctrineExtensions\Query\Mysql\CharLength
                 collate: DoctrineExtensions\Query\Mysql\Collate
                 concat_ws: DoctrineExtensions\Query\Mysql\ConcatWs
                 countif: DoctrineExtensions\Query\Mysql\CountIf
                 crc32: DoctrineExtensions\Query\Mysql\Crc32
                 degrees: DoctrineExtensions\Query\Mysql\Degrees
                 field: DoctrineExtensions\Query\Mysql\Field
                 find_in_set: DoctrineExtensions\Query\Mysql\FindInSet
                 greatest: DoctrineExtensions\Query\Mysql\Greatest
                 group_concat: DoctrineExtensions\Query\Mysql\GroupConcat
                 ifelse: DoctrineExtensions\Query\Mysql\IfElse
                 ifnull: DoctrineExtensions\Query\Mysql\IfNull
                 instr: DoctrineExtensions\Query\Mysql\Instr
                 least: DoctrineExtensions\Query\Mysql\Least
                 lpad: DoctrineExtensions\Query\Mysql\Lpad
                 match: DoctrineExtensions\Query\Mysql\MatchAgainst
                 md5: DoctrineExtensions\Query\Mysql\Md5
                 nullif: DoctrineExtensions\Query\Mysql\NullIf
                 radians: DoctrineExtensions\Query\Mysql\Radians
                 regexp: DoctrineExtensions\Query\Mysql\Regexp
                 replace: DoctrineExtensions\Query\Mysql\Replace
                 rpad: DoctrineExtensions\Query\Mysql\Rpad
                 sha1: DoctrineExtensions\Query\Mysql\Sha1
                 sha2: DoctrineExtensions\Query\Mysql\Sha2
                 soundex: DoctrineExtensions\Query\Mysql\Soundex
                 str_to_date: DoctrineExtensions\Query\Mysql\StrToDate
                 substring_index: DoctrineExtensions\Query\Mysql\SubstringIndex
                 uuid_short: DoctrineExtensions\Query\Mysql\UuidShort
                 hex: DoctrineExtensions\Query\Mysql\Hex
                 unhex: DoctrineExtensions\Query\Mysql\Unhex

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

avanzu_admin_theme:
    #use_assetic: false
    bower_bin: "bower "

jms_i18n_routing:
    default_locale: fr
    locales: [fr, en, es]
    strategy: prefix_except_default


jms_serializer:
    property_naming: 
        id: 'jms_serializer.camel_case_naming_strategy'



fos_user:
    db_driver: orm
    firewall_name: main
    from_email:
        address:        info@pass-sante.net
        sender_name:    PASS SANTE MOUSSO
    user_class: PS\UtilisateurBundle\Entity\Utilisateur
    group:
        group_class: PS\UtilisateurBundle\Entity\Groupe
    registration:
        form:
            type: app_user_registration
            #handler: app.form.handler.registration
            #factory: app_registration_factory
            validation_groups: [Default, Registration]

    profile:
        form:
            validation_groups: [Default, Profile]
            type: app_user_profile_edit
    resetting:
        form:
            type: app_user_reset_password
        #retry_ttl: 
        email:
            from_email:
                address:        info@pass-sante.net
                sender_name:    PASS SANTE MOUSSO


lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'
    
    encoder:
        # token encoder/decoder service - default implementation based on the namshi/jose library
        service:           lexik_jwt_authentication.encoder.lcobucci
    token_extractors:
        authorization_header:      # look for a token as Authorization Header
            enabled: true
            prefix:  Bearer
            name:    Authorization
        cookie:                    # check token in a cookie
            enabled: false
            name:    BEARER
        query_parameter:           # check token in query string parameter
            enabled: true
            name:    bearer



fos_rest:
    versioning:
      enabled: true
      resolvers:
        query: true
    # …
    disable_csrf_role: ROLE_API
    routing_loader:
        default_format: json
        include_format: false
    serializer:
        serialize_null: true
    view:
        view_response_listener: 'force'
    param_fetcher_listener:
        enabled: true
    exception:
        enabled: true
        messages:
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': true
        codes:
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': 404
            
    format_listener:
        rules:
            - { path: '^/api/', priorities: ['json'], fallback_format: 'json' } 
            - { path: '^/', priorities: ['text/html', '*/*'], fallback_format: html, prefer_extension: true } # converti les reponses des URL commencant par api en JSON


knp_paginator:
    page_range: 50                     # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: 'KnpPaginatorBundle:Pagination:twitter_bootstrap_v4_pagination.html.twig'     # sliding pagination controls template
        sortable: 'KnpPaginatorBundle:Pagination:sortable_link.html.twig' # sort link template


apy_data_grid:
    no_result_message: Aucune donnée disponible!
    # theme: '::blocks.html.twig'
    limits: [50, 100, 200]


sc_datetimepicker:
    picker: ~



nelmio_cors:
    paths:
        '^/api':
            allow_origin: ['*', 'http://localhost:8100']
            allow_credentials: true
            allow_headers: ['Origin', 'X-Requested-With', 'Content-Type', 'Accept', 'content-type', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'PATCH', 'OPTIONS']
            max_age: 3600
            