# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    erase_credentials: false
    encoders:
        old:
            algorithm: sha512
        new:
            algorithm: bcrypt
            cost: 13

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        #in_memory:
            #memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username
        jwt:
            lexik_jwt: ~ 

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  /api/login
            stateless: true
            anonymous: true
            #provider: jwt
            form_login:
                check_path: /api/login
                username_parameter: _username
                password_parameter: _password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        mobile_login:
            pattern:  /api/v2/login
            stateless: true
            anonymous: true
            provider: fos_userbundle
            form_login:
                check_path: /api/v2/login
                username_parameter: _username
                password_parameter: _password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        rest:
            pattern:   ^/api
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            pattern: ^/
            anonymous: true
            #anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            form_login:
                provider: fos_userbundle
                login_path: fos_user_security_login
                check_path: psm_login_check
                default_target_path: gestion_homepage
                #success_handler: redirect.after.login

            logout:
                path: psm_logout
                target: fos_user_security_login
                handlers: [psm_logoutlistener]
            remember_me:
                key:        %secret%
                lifetime: 604800 # 1 week in seconds
                path:     gestion_homepage
                secure: true

    role_hierarchy:
        ROLE_RECEPTION: ROLE_ASSISTANT
        ROLE_INFIRMIER: ROLE_ASSISTANT
        #ROLE_ADMIN: ROLE_CUSTOMER
        #ROLE_ADMIN_SUP: ROLE_CUSTOMER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
        # Liste des pages accessibles à tous les utilisateurs (ne pas toucher)
        - { path: ^/_wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/gestion/patient/new$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login$, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/profil$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/patients/([0-9]+)$, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api/v2/login$, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api/v2/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v2/profil$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v2/reset-password, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v2/update-password, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v2/patients/([0-9]+), role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/((fr|es|en)/)?admin/parametre/specialite/medecins, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/((fr|es|en)/)?admin/config/medecin/([0-9]+)/specialites, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/((fr|es|en)/)?admin/config/utilisateur/([0-9]+)/code, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/((fr|es|en)/)?admin/config/utilisateur, role: [ROLE_INFIRMIER, ROLE_RECEPTION, ROLE_ADMIN,  ROLE_ADMIN_SUP, ROLE_ADMIN_CORPORATE, ROLE_ADMIN_LOCAL] }
        # PAGES ACCESSIBLES AUX ADMINISTRATEURS
        - { path: ^/((fr|es|en)/)?admin/config/utilisateur/unregister, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/reset-password$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/((fr|es|en)/)?admin/consultation/historique$, role: [ROLE_CUSTOMER, ROLE_MEDECIN] }
        # PAGES ACCESSIBLES AUX ADMINISTRATEURS
        # - { path: ^/((fr|es|en)/)?admin/config/, role: [ROLE_ADMIN, ROLE_ADMIN_CORPORATE, ROLE_ADMIN_LOCAL, ROLE_ADMIN_SUP] }
        - { path: ^/((fr|es|en)/)?admin/specialite, role: [ROLE_ADMIN, ROLE_ADMIN_CORPORATE, ROLE_MEDECIN, ROLE_ASSISTANT]}
        - { path: ^/((fr|es|en)/)?admin/rendezvous/, role: IS_AUTHENTICATED_FULLY}
        - { path: ^/((fr|es|en)/)?admin/rendezvous/add, role: [ROLE_MEDECIN, ROLE_INFIRMIER, ROLE_ASSISTANT, ROLE_CUSTOMER]}
        - { path: ^/((fr|es|en)/)?admin/rendezvous/edit/([0-9]+)$, role: [ROLE_MEDECIN, ROLE_INFIRMIER, ROLE_ASSISTANT, ROLE_CUSTOMER]}
        - { path: ^/((fr|es|en)/)?admin/rendezvous/annuler/([0-9]+)$, role: [ROLE_MEDECIN, ROLE_INFIRMIER, ROLE_ASSISTANT, ROLE_CUSTOMER]}
        - { path: ^/((fr|es|en)/)?admin/gestion/corporate, role: [ROLE_ADMIN, ROLE_ADMIN_CORPORATE, ROLE_ADMIN_LOCAL, ROLE_ADMIN_SUP]}
        - { path: ^/((fr|es|en)/)?admin/gestion/faq/?$,role: IS_AUTHENTICATED_FULLY}
        - { path: ^/((fr|es|en)/)?admin/gestion/patient, role: IS_AUTHENTICATED_FULLY}
        - { path: ^/((fr|es|en)/)?admin/gestion/vaccination, role: IS_AUTHENTICATED_FULLY}
        - { path: ^/((fr|es|en)/)?admin/gestion/questionnaire, role: IS_AUTHENTICATED_FULLY}
        - { path: ^/((fr|es|en)/)?admin/gestion/questionnaire-depistage/([0-9]+)/(stat|map)$, role: ROLE_ADMIN}
        - { path: ^/((fr|es|en)/)?admin/gestion/urgence, role: [ROLE_URGENTISTE, ROLE_CUSTOMER]}
        - { path: ^/((fr|es|en)/)?admin/gestion/historique-urgence$, role: [ROLE_URGENTISTE, ROLE_CUSTOMER]}
        - { path: ^/((fr|es|en)/)?admin/gestion/historique-urgence/([0-9]+)/liste, role: [ROLE_URGENTISTE, ROLE_CUSTOMER]}
        - { path: ^/((fr|es|en)/)?admin/gestion/historique-urgence, role: [ROLE_URGENTISTE]}
        - { path: ^/((fr|es|en)/)?admin/gestion/abonnement, role: ROLE_CUSTOMER}
        - { path: ^/((fr|es|en)/)?admin/gestion/admission, role: [ROLE_RECEPTION, ROLE_INFIRMIER] }
        - { path: ^/((fr|es|en)/)?admin/gestion/fiche/(new|edit|search), role: [ROLE_MEDECIN]  }
        - { path: ^/((fr|es|en)/)?admin/gestion/fiche/?(([0-9]+)/show)?, role: [ROLE_MEDECIN, ROLE_CUSTOMER]  }
        - { path: ^/((fr|es|en)/)?admin/gestion/, role: [ROLE_ADMIN, ROLE_ADMIN_CORPORATE, ROLE_ADMIN_LOCAL, ROLE_ADMIN_SUP]  }
        - { path: ^/((fr|es|en)/)?admin/parametre/hopital, role: [ROLE_ADMIN, ROLE_ADMIN_CORPORATE, ROLE_ADMIN_LOCAL, ROLE_ADMIN_SUP]}
        - { path: ^/((fr|es|en)/)?admin/pharmacie/historique, role: [ROLE_CUSTOMER, ROLE_PHARMACIE, ROLE_ADMIN] }
        - { path: ^/((fr|es|en)/)?admin/pharmacie/ordonnances, role: [ROLE_CUSTOMER, ROLE_PHARMACIE] }
        - { path: ^/((fr|es|en)/)?admin/pharmacie/ordonnances/([0-9]+)$, role: [ROLE_PHARMACIE] }
        - { path: ^/((fr|es|en)/)?admin/pharmacie/medicaments, role: [ROLE_CUSTOMER, ROLE_PHARMACIE] }
        - { path: ^/((fr|es|en)/)?admin/pharmacie/verif, role: IS_AUTHENTICATED_FULLY  }
        - { path: ^/((fr|es|en)/)?admin/pharmacie/garde, role: IS_AUTHENTICATED_FULLY  }
        - { path: ^/((fr|es|en)/)?admin/pharmacie/, role: [ROLE_PHARMACIE, ROLE_ADMIN, ROLE_ADMIN_SUP]  }
        - { path: ^/((fr|es|en)/)?admin/infirmier/, role: [ROLE_ADMIN_SUP, ROLE_ADMIN, ROLE_INFIRMIER] }
        #- { path: ^/register/, role: ROLE_ADMIN }
        # PAGES ACCESSIBLES AUX CENTRES DE SANTE
        #- { path: ^/admin/consultation/, role: ROLE_MEDECIN }
        # PAGES ACCESSIBLES AUX UTILISATEURS CONNECTES
        - { path: ^/change-password, role: ROLE_CUSTOMER }
        - { path: ^/reseting$, role: ROLE_CUSTOMER }
        - { path: ^/((fr|es|en)/)?admin/patient/, role: [ROLE_CUSTOMER, ROLE_RECEPTION, ROLE_ADMIN_LOCAL, ROLE_ADMIN_CORPORATE, ROLE_PHARMACIE, ROLE_ADMIN_SUP, ROLE_ADMIN] }
        - { path: ^/((fr|es|en)/)?admin/, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/, role: [ROLE_CUSTOMER, ROLE_MEDECIN] }
        # PAGES ACCESSIBLES À TOUS
        - { path: ^.*, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

        #, requires_channel: https