<?php

namespace PS\ParametreBundle\Repository;

/**
 * CategorieTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
