<?php

namespace PS\ParametreBundle\Repository;

/**
 * ExamenAffectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamenAffectionRepository extends \Doctrine\ORM\EntityRepository
{
}
