<?php

namespace PS\ParametreBundle\Repository;

/**
 * InfoPharmacieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoHopitalRepository extends \Doctrine\ORM\EntityRepository
{
}
