<?php

namespace PS\ParametreBundle\Repository;

/**
 * LienParenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LienParenteRepository extends \Doctrine\ORM\EntityRepository
{
}
