<?php

namespace PS\ParametreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AffectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneAssuranceRepository extends EntityRepository
{
    public function findByPatient($patient)
    {

    }


    public function deleteByPatient($patient, $id)
    {

    }

    public function updateByPatient($patient, $id)
    {
        
    }
}
