<?php

namespace PS\ParametreBundle\Repository;

/**
 * ListeOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
