<?php

namespace PS\ParametreBundle\Repository;

/**
 * ListeExamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeExamenRepository extends \Doctrine\ORM\EntityRepository
{
}
