<?php

namespace PS\ParametreBundle\Repository;

/**
 * ListeAntecedentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeAntecedentRepository extends \Doctrine\ORM\EntityRepository
{
}
