<?php

namespace PS\ParametreBundle\Repository;

/**
 * PatientTraitementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientTraitementRepository extends \Doctrine\ORM\EntityRepository
{
}
