<?php

namespace PS\ParametreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MedecinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientVaccinRepository extends EntityRepository
{
    public function findByPatient($id)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('a.id, a.vaccin, a.date, a.rappel')
            ->from('ParametreBundle:PatientVaccin', 'a')
            ->where("a.patient = :id")
            ->orderBy('a.date',   'DESC')
            ->orderBy('a.rappel', 'DESC')
            ->setParameter('id', $id);

        return $qb->getQuery()->getResult();

    }


    public function countRappelByPatient($id)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('COUNT(v.id)')
            ->from('ParametreBundle:PatientVaccin', 'v')
            ->where("v.patient = :id")
            ->setParameter('id', $id);
        return $qb->getQuery()->getSingleScalarResult();
    }


    public function findRappelByPatient($id, $date = null, $limit = null, $offset = null)
    {
        $params= ['id' => $id];
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('a.vaccin, a.date, a.rappel')
            ->from('ParametreBundle:PatientVaccin', 'a')
            ->where("a.patient = :id");
           


        if ($date) {
            $qb->andWhere('a.date =  :date');
            $params['date'] = $date;
        }


        $qb->orderBy('a.date',   'DESC')
            ->orderBy('a.rappel', 'DESC')
            
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->setParameter('id', $id);

        return $qb->getQuery()->getResult();
    }


    public function findOneByPatient($id, $vaccin)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('a.id, a.vaccin, a.date, a.rappel')
            ->from('ParametreBundle:PatientVaccin', 'a')
            ->where("a.patient = :id")
            ->andWhere('a.id = :vaccin')
            ->setParameter('id', $id)
            ->setParameter('vaccin', $vaccin);

        return $qb->getQuery()->getOneOrNullResult();

    }

}
