<?php

namespace PS\ParametreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MedecinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientAssuranceRepository extends EntityRepository
{
    public function findByPatient($id)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('a.id, a.assurance, a.taux, a.numero')
            ->from('ParametreBundle:PatientAssurance', 'a')
            ->where("a.patient = :id")
            ->orderBy('a.id',   'DESC')
            ->setParameter('id', $id);

        return $qb->getQuery()->getResult();

    }

    public function findOneByPatient($id, $assurance)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('a.id, a.assurance, a.taux, a.numero')
            ->from('ParametreBundle:PatientAssurance', 'a')
            ->where("a.patient = :id")
            ->andWhere('a.id = :assurance')
            ->setParameter('id', $id)
            ->setParameter('assurance', $assurance);

        return $qb->getQuery()->getOneOrNullResult();

    }

}
