<?php

namespace PS\ParametreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MedecinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientMedecinRepository extends EntityRepository
{
    public function findByPatient($id)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('m.id, m.medecin, m.contact, m.specialite')
            ->from('ParametreBundle:PatientMedecin', 'm')
            ->where("m.patient = :id")
            ->orderBy('m.id',   'DESC')
            ->setParameter('id', $id);

        return $qb->getQuery()->getResult();

    }

    public function findOneByPatient($id, $medecin)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('m.id, m.medecin, m.contact, m.specialite')
            ->from('ParametreBundle:PatientMedecin', 'm')
            ->where("m.patient = :id")
            ->andWhere('m.id = :medecin')
            ->setParameter('id', $id)
            ->setParameter('medecin', $medecin);

        return $qb->getQuery()->getOneOrNullResult();

    }

}
