<?php

namespace PS\ParametreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * AnalyseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaysRepository extends EntityRepository
{
    /**
     * On teste si le couple PIN + ID existe
     * @param  int $pin         
     * @param  int $identifiant 
     * @return int
     */
    public function exists($pays)
    {
        $em = $this->getEntityManager();
        $qb = $em
            ->createQuery('SELECT a.id FROM ParametreBundle:Pays a WHERE a.id = ?1 OR a.nom = ?2')
            ->setParameter(1, $pays)
            ->setParameter(2, $pays);
        try {
          $result = $qb->getOneOrNullResult(); 
        } catch (NoResultException $e) {
            $result = null;
        }

        return $result;
    }
}
