<?php

namespace PS\ParametreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AnalyseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialiteRepository extends EntityRepository
{
    public function getForMedecin($medecin)
    {
        $em = $this->getEntityManager();

        $qb = $em->createQueryBuilder();

        $qb->select("s")
            ->from('GestionBundle:MedecinSpecialite', 'ms')
            ->join('ms.medecin', 'm')
            ->join('ParametreBundle:Specialite', 's', 'WITH', 'ms.specialite = s.id')
            ->andWhere('m.id = :medecin')
            
            
            ->setParameter('medecin', $medecin);

        //dump($qb->getQuery()->getSQL());exit;

        //$count = $qb->getSingleScalarResult();
        return $qb;
    }
}
