<?php

namespace PS\ParametreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MedecinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelephoneRepository extends EntityRepository
{
    public function findByPatient($id)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('a.id, a.nom, a.numero, a.lien')
            ->from('ParametreBundle:Telephone', 'a')
            ->where("a.patient = :id")
            ->orderBy('a.id',   'DESC')
            ->setParameter('id', $id);

        return $qb->getQuery()->getResult();

    }


    public function findOneByPatient($id, $telephone)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('a.id, a.nom, a.numero, a.lien')
            ->from('ParametreBundle:Telephone', 'a')
            ->where("a.patient = :id")
            ->andWhere('a.id = :telephone')
            ->setParameter('id', $id)
            ->setParameter('telephone', $telephone);

        return $qb->getQuery()->getOneOrNullResult();

    }

}
