<?php

namespace PS\ParametreBundle\Repository;

/**
 * TypeHopitalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeHopitalRepository extends \Doctrine\ORM\EntityRepository
{
}
