<?php

namespace PS\ParametreBundle\Repository;

/**
 * TypeStatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeStatutRepository extends \Doctrine\ORM\EntityRepository
{
}
