admin_parametre_allergie_index:
    path:     /
    defaults: { _controller: "ParametreBundle:Allergie:index" }
    methods:  GET

admin_parametre_allergie_show:
    path:     /{id}/show
    defaults: { _controller: "ParametreBundle:Allergie:show" }
    methods:  GET

admin_parametre_allergie_new:
    path:     /new
    defaults: { _controller: "ParametreBundle:Allergie:new" }
    methods:  [GET, POST]

admin_parametre_allergie_edit:
    path:     /{id}/edit
    defaults: { _controller: "ParametreBundle:Allergie:edit" }
    methods:  [GET, POST]

admin_parametre_allergie_delete:
    path:     /{id}/delete
    defaults: { _controller: "ParametreBundle:Allergie:delete" }
    methods:  DELETE
