admin_parametre_analyse_index:
    path:     /
    defaults: { _controller: "ParametreBundle:Analyse:index" }
    methods:  GET

admin_parametre_analyse_show:
    path:     /{id}/show
    defaults: { _controller: "ParametreBundle:Analyse:show" }
    methods:  GET

admin_parametre_analyse_new:
    path:     /new
    defaults: { _controller: "ParametreBundle:Analyse:new" }
    methods:  [GET, POST]

admin_parametre_analyse_edit:
    path:     /{id}/edit
    defaults: { _controller: "ParametreBundle:Analyse:edit" }
    methods:  [GET, POST]

admin_parametre_analyse_delete:
    path:     /{id}/delete
    defaults: { _controller: "ParametreBundle:Analyse:delete" }
    methods:  DELETE
