admin_parametre_assurance_index:
    path:     /
    defaults: { _controller: "ParametreBundle:Assurance:index" }
   

admin_parametre_assurance_show:
    path:     /{id}/show
    defaults: { _controller: "ParametreBundle:Assurance:show" }
    methods:  GET

admin_parametre_assurance_new:
    path:     /new
    defaults: { _controller: "ParametreBundle:Assurance:new" }
    methods:  [GET, POST]

admin_parametre_assurance_edit:
    path:     /{id}/edit
    defaults: { _controller: "ParametreBundle:Assurance:edit" }
    methods:  [GET, POST]

admin_parametre_assurance_delete:
    path:     /{id}/delete
    defaults: { _controller: "ParametreBundle:Assurance:delete" }
    methods:  DELETE
