admin_parametre_attribut_index:
    path:     /
    defaults: { _controller: "ParametreBundle:Attribut:index" }
    methods:  [GET,POST]

admin_parametre_attribut_show:
    path:     /{id}/show
    defaults: { _controller: "ParametreBundle:Attribut:show" }
    methods:  GET

admin_parametre_attribut_new:
    path:     /new
    defaults: { _controller: "ParametreBundle:Attribut:new" }
    methods:  [GET, POST]

admin_parametre_attribut_edit:
    path:     /{id}/edit
    defaults: { _controller: "ParametreBundle:Attribut:edit" }
    methods:  [GET, POST]

admin_parametre_attribut_delete:
    path:     /{id}/delete
    defaults: { _controller: "ParametreBundle:Attribut:delete" }
    methods:  DELETE
