admin_parametre_etat_index:
    path:     /
    defaults: { _controller: "ParametreBundle:Etat:index" }
    methods:  [GET,POST]

admin_parametre_etat_show:
    path:     /{id}/show
    defaults: { _controller: "ParametreBundle:Etat:show" }
    methods:  GET

admin_parametre_etat_new:
    path:     /new
    defaults: { _controller: "ParametreBundle:Etat:new" }
    methods:  [GET, POST]

admin_parametre_etat_edit:
    path:     /{id}/edit
    defaults: { _controller: "ParametreBundle:Etat:edit" }
    methods:  [GET, POST]

admin_parametre_etat_delete:
    path:     /{id}/delete
    defaults: { _controller: "ParametreBundle:Etat:delete" }
    methods:  DELETE
