admin_parametre_groupesanguin_index:
    path:     /
    defaults: { _controller: "ParametreBundle:GroupeSanguin:index" }
    methods:  GET

admin_parametre_groupesanguin_show:
    path:     /{id}/show
    defaults: { _controller: "ParametreBundle:GroupeSanguin:show" }
    methods:  GET

admin_parametre_groupesanguin_new:
    path:     /new
    defaults: { _controller: "ParametreBundle:GroupeSanguin:new" }
    methods:  [GET, POST]

admin_parametre_groupesanguin_edit:
    path:     /{id}/edit
    defaults: { _controller: "ParametreBundle:GroupeSanguin:edit" }
    methods:  [GET, POST]

admin_parametre_groupesanguin_delete:
    path:     /{id}/delete
    defaults: { _controller: "ParametreBundle:GroupeSanguin:delete" }
    methods:  DELETE
