admin_parametre_image_index:
    path:     /
    defaults: { _controller: "ParametreBundle:Image:index" }
    methods:  GET

admin_parametre_image_show:
    path:     /{id}/show
    defaults: { _controller: "ParametreBundle:Image:show" }
    methods:  GET

admin_parametre_image_new:
    path:     /new
    defaults: { _controller: "ParametreBundle:Image:new" }
    methods:  [GET, POST]

admin_parametre_image_edit:
    path:     /{id}/edit
    defaults: { _controller: "ParametreBundle:Image:edit" }
    methods:  [GET, POST]

admin_parametre_image_delete:
    path:     /{id}/delete
    defaults: { _controller: "ParametreBundle:Image:delete" }
    methods:  DELETE
