admin_parametre_nationalite_index:
    path:     /
    defaults: { _controller: "ParametreBundle:Nationalite:index" }
    methods:  [GET, POST]

admin_parametre_nationalite_show:
    path:     /{id}/show
    defaults: { _controller: "ParametreBundle:Nationalite:show" }
    methods:  GET

admin_parametre_nationalite_new:
    path:     /new
    defaults: { _controller: "ParametreBundle:Nationalite:new" }
    methods:  [GET, POST]

admin_parametre_nationalite_edit:
    path:     /{id}/edit
    defaults: { _controller: "ParametreBundle:Nationalite:edit" }
    methods:  [GET, POST]

admin_parametre_nationalite_delete:
    path:     /{id}/delete
    defaults: { _controller: "ParametreBundle:Nationalite:delete" }
    methods:  DELETE
