admin_parametre_permission_index:
    path:     /index
    defaults: { _controller: ParametreBundle:Permission:index }

admin_parametre_permission_new:
    path:     /{module}/new
    defaults: { _controller: ParametreBundle:Permission:new }

admin_parametre_permission_edit:
    path:     /{permission}/edit
    defaults: { _controller: ParametreBundle:Permission:edit }

admin_parametre_permission_delete:
    path:     /{permission}/delete
    defaults: { _controller: ParametreBundle:Permission:delete }


admin_parametre_permission_role:
    path:     /roles
    defaults: { _controller: ParametreBundle:Permission:roles }