admin_parametre_religion_index:
    path:     /
    defaults: { _controller: "ParametreBundle:Religion:index" }
    methods:  [GET, POST]

admin_parametre_religion_show:
    path:     /{id}/show
    defaults: { _controller: "ParametreBundle:Religion:show" }
    methods:  GET

admin_parametre_religion_new:
    path:     /new
    defaults: { _controller: "ParametreBundle:Religion:new" }
    methods:  [GET, POST]

admin_parametre_religion_edit:
    path:     /{id}/edit
    defaults: { _controller: "ParametreBundle:Religion:edit" }
    methods:  [GET, POST]

admin_parametre_religion_delete:
    path:     /{id}/delete
    defaults: { _controller: "ParametreBundle:Religion:delete" }
    methods:  DELETE
