admin_parametre_vaccin_index:
    path:     /
    defaults: { _controller: "ParametreBundle:Vaccin:index" }
    methods:  GET

admin_parametre_vaccin_show:
    path:     /{id}/show
    defaults: { _controller: "ParametreBundle:Vaccin:show" }
    methods:  GET

admin_parametre_vaccin_new:
    path:     /new
    defaults: { _controller: "ParametreBundle:Vaccin:new" }
    methods:  [GET, POST]

admin_parametre_vaccin_edit:
    path:     /{id}/edit
    defaults: { _controller: "ParametreBundle:Vaccin:edit" }
    methods:  [GET, POST]

admin_parametre_vaccin_delete:
    path:     /{id}/delete
    defaults: { _controller: "ParametreBundle:Vaccin:delete" }
    methods:  DELETE
