<?php

namespace PS\GestionBundle\Repository;

/**
 * AdmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdmissionRepository extends \Doctrine\ORM\EntityRepository
{
}
