<?php

namespace PS\GestionBundle\Repository;

/**
 * AlerteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlerteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllPatient($patient, $start, $end)
    {
        $sql           = <<<SQL
        SELECT 
            DATE(`date_debut`) AS start,
            libelle AS title
            id,
            valeur
            FROM alerte
        WHERE patient_id = :patient_id
SQL;
    }


     /**
     * @param $date
     */
    private function convertDate($date)
    {
        if ($date) {
            return (new \DateTime($date))->format('Y-m-d');
        }
    }
}
