<?php

namespace PS\GestionBundle\Repository;

/**
 * ConsultationAntecedentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultationAntecedentRepository extends \Doctrine\ORM\EntityRepository
{
}
