<?php

namespace PS\GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MedecinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultationTraitementsRepository extends EntityRepository
{

    public function findByPatientConsultation($patient, $consultation)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('c', 'c1')
            ->from('GestionBundle:ConsultationTraitements', 'c')
            ->innerJoin("c.consultation", "c1")
            ->where('c1.patient = :patient_id')
            ->andWhere('c.consultation = :consultation_id')
            
            ->setParameter('patient_id', $patient)
            ->setParameter('consultation_id', $consultation);

        return $qb->getQuery()->getResult();
    }

    
}
