<?php

namespace PS\GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MedecinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorporateRepository extends EntityRepository
{
    public function totalLivraison($corporate)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('SUM(l.qteLivraison) AS s')
                ->from('GestionBundle:Commande', 'c1')
                ->join('c1.corporate', 'c')
                ->join('c1.livraisons', 'l')
                ->where('c1.corporate = :corporate')
                ->setParameter('corporate', $corporate)
                ->groupBy('l.commande');

         return $qb->getQuery()->getOneOrNullResult();
    }

}
