<?php

namespace PS\GestionBundle\Repository;

/**
 * DestinataireMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestinataireMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
