<?php

namespace PS\GestionBundle\Repository;

/**
 * DiagnosticQuestionnaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiagnosticQuestionnaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function diagnostic($questionnaire, $valeur)
    {
         $qb = $this->createQueryBuilder('g');
        $qb
            ->where("g.questionnaire = :questionnaire")
            ->andWhere(':valeur BETWEEN g.pourcentageMin AND g.pourcentageMax')
            ->setParameter('questionnaire', $questionnaire)
            ->setParameter('valeur', $valeur);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
