<?php

namespace PS\GestionBundle\Repository;

/**
 * DisponibiliteMedicamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisponibiliteMedicamentRepository extends \Doctrine\ORM\EntityRepository
{
}
