<?php

namespace PS\GestionBundle\Repository;

/**
 * DonneeQuestionnaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonneeQuestionnaireRepository extends \Doctrine\ORM\EntityRepository
{
}
