<?php

namespace PS\GestionBundle\Repository;

/**
 * FicheAnalyseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheAnalyseRepository extends \Doctrine\ORM\EntityRepository
{
}
