<?php

namespace PS\GestionBundle\Repository;

/**
 * FicheExamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheExamenRepository extends \Doctrine\ORM\EntityRepository
{
}
