<?php

namespace PS\GestionBundle\Repository;

/**
 * FicheGcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheGcRepository extends \Doctrine\ORM\EntityRepository
{
}
