<?php

namespace PS\GestionBundle\Repository;

/**
 * FicheTraitementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheTraitementRepository extends \Doctrine\ORM\EntityRepository
{
}
