<?php

namespace PS\GestionBundle\Repository;

/**
 * FicheParamCliniqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheParamCliniqueRepository extends \Doctrine\ORM\EntityRepository
{
}
