<?php

namespace PS\GestionBundle\Repository;

/**
 * FicheGlycemieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheGlycemieRepository extends \Doctrine\ORM\EntityRepository
{
}
