<?php

namespace PS\GestionBundle\Repository;

/**
 * FicheAntecedentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheAntecedentRepository extends \Doctrine\ORM\EntityRepository
{
}
