<?php

namespace PS\GestionBundle\Repository;

/**
 * FicheConstanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheConstanteRepository extends \Doctrine\ORM\EntityRepository
{
}
