<?php

namespace PS\GestionBundle\Repository;

/**
 * FicheComplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheComplicationRepository extends \Doctrine\ORM\EntityRepository
{
}
