<?php

namespace PS\GestionBundle\Repository;

/**
 * FicheAffectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheAffectionRepository extends \Doctrine\ORM\EntityRepository
{
    public function last($patient)
    {
        $qb = $this->createQueryBuilder('l');
        $qb
            ->andWhere('l.patient = :patient')
            ->setParameter('patient', $patient)
            ->orderBy('l.date', 'DESC')
            ->setMaxResults(1);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
