<?php

namespace PS\GestionBundle\Repository;

/**
 * GardePharmacieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GardePharmacieRepository extends \Doctrine\ORM\EntityRepository
{
}
