<?php

namespace PS\GestionBundle\Repository;

/**
 * HistoriqueUrgenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueUrgenceRepository extends \Doctrine\ORM\EntityRepository
{
}
