<?php

namespace PS\GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InfirmierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfirmierRepository extends EntityRepository
{
    public function findByMedecin($medecin)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('i')
            ->from('GestionBundle:Infirmier', 'i')
            ->where('i.medecin = :medecin')
            ->setParameter('medecin', $medecin);

        return $qb->getQuery()->getSingleScalarResult();
    }

}
