<?php

namespace PS\GestionBundle\Repository;

/**
 * InfoConsultationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoConsultationRepository extends \Doctrine\ORM\EntityRepository
{
}
