<?php

namespace PS\GestionBundle\Repository;

/**
 * InfoPharmacieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoPharmacieRepository extends \Doctrine\ORM\EntityRepository
{
}
