<?php

namespace PS\GestionBundle\Repository;

/**
 * LigneAntecedentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneAntecedentRepository extends \Doctrine\ORM\EntityRepository
{
}
