<?php

namespace PS\GestionBundle\Repository;

/**
 * LigneExamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneExamenRepository extends \Doctrine\ORM\EntityRepository
{
}
