<?php

namespace PS\GestionBundle\Repository;

/**
 * LigneQuestionnaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneQuestionnaireRepository extends \Doctrine\ORM\EntityRepository
{
}
