<?php

namespace PS\GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LigneAnalyseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicamentPharmacieRepository extends EntityRepository
{
    public function findHistorique($id)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('p.date', 'm.medicament')
            ->from('GestionBundle:MedicamentPharmacie', 'p')
            ->join('p.user', 'u')
            ->join('p.medicament', 'm')
            ->join('m.consultation', 'c')
            ->where("m.consultation = :id")
            ->setParameter('id', $id);

        return $qb->getQuery()->getSQL();
    }


    public function findByDate($dateOperation)
    {

    }
}
