<?php

namespace PS\GestionBundle\Repository;

use PS\GestionBundle\Entity\Paiement;

/**
 * PaiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByReference($reference): ?Paiement
    {
        return $this->createQueryBuilder('p')
            ->andWhere('p.referencePayement = :reference')
            ->setParameter('reference', $reference)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
