<?php

namespace PS\GestionBundle\Repository;

/**
 * PatientDonneeAffectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassClientRepository extends \Doctrine\ORM\EntityRepository
{
}
