<?php

namespace PS\GestionBundle\Repository;

/**
 * PatientQuestionnaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientQuestionnaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySpecialites($specialites, $statut = false)
    {
        

        $qb = $this->createQueryBuilder('p');


        $qb
            ->join('GestionBundle:QuestionnaireDepistage', 'q', 'WITH', 'p.questionnaire = q.id')
            ->join('q.specialites', 's');

        $params = [];
        
        foreach ($specialites as $index => $specialite) {
           
            $qb->orWhere('s.id = :specialite_'.($index+1));
            $params['specialite_'.($index+1)] = $specialite->getId(); 
        }

        $qb->andWhere($qb->expr()->eq('p.statut', ':statut'));
        $params['statut'] = false;

         $qb->orderBy('p.date', 'DESC');

        $qb->setParameters($params);

        //dump($qb->getQuery()->getSQL(), $params);exit;

        return $qb->getQuery()->getResult();
       
    }


    public function minYear($questionnaire)
    {
        $query = $this->getEntityManager()->createQuery('SELECT MIN(YEAR(p.date)) FROM GestionBundle:PatientQuestionnaire p WHERE p.questionnaire = :questionnaire');

        $query->setParameters(compact('questionnaire'));

        $annee = intval($query->getSingleScalarResult());


        
        return $annee ?: date('Y');
    }

}
