<?php

namespace PS\GestionBundle\Repository;

/**
 * PositionPatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositionPatientRepository extends \Doctrine\ORM\EntityRepository
{
}
