<?php

namespace PS\GestionBundle\Repository;

/**
 * QuestionnaireDepistageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionnaireDepistageRepository extends \Doctrine\ORM\EntityRepository
{
}
