<?php

namespace PS\GestionBundle\Repository;

/**
 * StatistiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatistiqueRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBySpecialite($specialite)
    {
        $em = $this->getEntityManager();

        $qb = $em->createQueryBuilder();
        return $qb->select("s")
            ->from("GestionBundle:Statistique", 's')
            ->join('s.champ','c')
            ->join('PSSpecialiteBundle:Etape', 'e', 'WITH', 'c.etape = e.id')
            ->andWhere('e.specialite = :specialite')
            ->setParameter('specialite', $specialite);
    }
}
