<?php

namespace PS\GestionBundle\Repository;

/**
 * TraitementQuestionnaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraitementQuestionnaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function weekkStats($mois, $annee)
    {
        
    }
}
