<?php

namespace PS\GestionBundle\Repository;

/**
 * ValeurLigneQuestionnaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValeurLigneQuestionnaireRepository extends \Doctrine\ORM\EntityRepository
{
}
