<?php

namespace PS\GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MedecinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultationRepository extends EntityRepository
{
    public function findByPatient($id)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('c')
            ->from('GestionBundle:Consultation', 'c')
            ->where("c.patient = :id")
            ->orderBy('c.id',   'DESC')
            ->setParameter('id', $id);

        return $qb->getQuery()->getResult();

    }

    public function findAllMedecin($id)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('c')
            ->from('GestionBundle:Consultation', 'c')
            ->leftJoin('c.medecin', 'm')
            ->addSelect('m')
            ->where("m.personne = :id")
            ->andWhere("m.id = c.medecin")
            ->orderBy('c.id',   'DESC')
            ->setParameter('id', $id);

        return $qb->getQuery()->getResult();

    }

    public function findAllPatient($id)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('c')
            ->from('GestionBundle:Consultation', 'c')
            ->leftJoin('c.patient', 'p')
            ->addSelect('p')
            ->where("p.personne = :id")
            ->andWhere("c.patient = p.id")
            ->orderBy('c.id',   'DESC')
            ->setParameter('id', $id);

        return $qb->getQuery()->getResult();

    }

}
