<?php

namespace PS\GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MedecinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientRepository extends EntityRepository
{
    public function findByPass($id, $pin)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('count(p)')
            ->from('ParametreBundle:Pass', 'p')
            ->where("p.identifiant = :id")
            ->andWhere('p.pin = :pin')
            ->andWhere('p.actif = 1')
            ->setParameter('id', $id)
            ->setParameter('pin', $pin);

        return $qb->getQuery()->getResult();
    }

    public function findByParam($id, $pin)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('p')
            ->from('GestionBundle:Patient', 'p')
            ->where("p.identifiant = :id")
            ->andWhere('p.pin = :pin')
            ->setParameter('id', $id)
            ->setParameter('pin', $pin);

        return $qb->getQuery()->getResult();
    }

    public function findPatient($id)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('p')
            ->from('GestionBundle:Patient', 'p')
            ->where("p.personne = :id")
            ->setParameter('id', $id);

        return $qb->getQuery()->getResult();

    }

    public function findSearch($nom)
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->leftjoin('a.personne','b')
            ->where("b.nom LIKE :nom")
//            ->orderBy('a.nom', 'ASC')
            ->setParameter('nom', '%' . $nom . '%');

        return $qb->getQuery()->getResult();

    }

    public function statistiqueSexe()
    {
        $qb = $this->createQueryBuilder('a');

        $qb->select('COUNT(a.id) as nbre, a.sexe')
            ->groupby("a.sexe");

        return $qb->getQuery()->getResult();

    }

}
