admin_gestion_faq_index:
    path:     /
    defaults: { _controller: "GestionBundle:Faq:index" }
    methods:  [GET, POST]

admin_gestion_faq_show:
    path:     /{id}/show
    defaults: { _controller: "GestionBundle:Faq:show" }
    methods:  GET



admin_gestion_faq_new:
    path:     /new
    defaults: { _controller: "GestionBundle:Faq:new" }
    methods:  [GET, POST]

admin_gestion_faq_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionBundle:Faq:edit" }
    methods:  [GET, POST]

admin_gestion_faq_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionBundle:Faq:delete" }
    methods:  DELETE
