admin_gestion_patient_index:
    path:     /
    defaults: { _controller: "GestionBundle:Patient:index" }
    methods:  GET

admin_gestion_patient_show:
    path:     /{id}/show
    defaults: { _controller: "GestionBundle:Patient:show" }
    methods:  GET

admin_gestion_patient_new:
    path:     /new
    defaults: { _controller: "GestionBundle:Patient:new" }
    methods:  [GET, POST]

admin_gestion_patient_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionBundle:Patient:edit" }
    methods:  [GET, POST]

admin_gestion_patient_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionBundle:Patient:delete" }
    methods:  DELETE
