admin_gestion_patient_info:
    path:     /info/{id}
    defaults: { _controller: "GestionBundle:Patient:info", id: null }
    methods:  GET

admin_gestion_patient_modifier:
    path:     /{id}/modifier
    defaults: { _controller: "GestionBundle:Patient:modifier" }
    methods:  [GET, POST]

admin_patient_historique_show:
    path:     /{id}/{id1}/historique
    defaults: { _controller: "GestionBundle:Consultation:historiqueShow" }
    methods:  GET

admin_patient_historique:
    path:     /historique
    defaults: { _controller: "GestionBundle:Consultation:historique" }
    methods:  [GET, POST]
