admin_gestion_site_index:
    path:     /
    defaults: { _controller: "GestionBundle:Site:index" }
    methods:  [GET, POST]

admin_gestion_site_show:
    path:     /{id}/show
    defaults: { _controller: "GestionBundle:Site:show" }
    methods:  GET

admin_gestion_site_new:
    path:     /new
    defaults: { _controller: "GestionBundle:Site:new" }
    methods:  [GET, POST]

admin_gestion_site_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionBundle:Site:edit" }
    methods:  [GET, POST]

admin_gestion_site_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionBundle:Site:delete" }
    methods:  DELETE
