admin_gestion_traitement_index:
    path:     /
    defaults: { _controller: "GestionBundle:Traitement:index" }
    methods:  GET

admin_gestion_traitement_show:
    path:     /{id}/show
    defaults: { _controller: "GestionBundle:Traitement:show" }
    methods:  GET

admin_gestion_traitement_new:
    path:     /new
    defaults: { _controller: "GestionBundle:Traitement:new" }
    methods:  [GET, POST]

admin_gestion_traitement_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionBundle:Traitement:edit" }
    methods:  [GET, POST]

admin_gestion_traitement_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionBundle:Traitement:delete" }
    methods:  DELETE
