services:
#    gestion.example:
#        class: PS\GestionBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

parameters:
    my_admin_bundle.show_user_listener.class: PS\GestionBundle\EventListener\MyShowUserListener
    my_admin_bundle.menu_listener.class: PS\GestionBundle\EventListener\MyMenuItemListListener
    my_admin_bundle.breadcrumb_listener.class: PS\GestionBundle\EventListener\MyMenuItemListListener
    my_admin_bundle.task_list_listener.class: PS\GestionBundle\EventListener\MyTaskListListener
    my_admin_bundle.notification_list_listener.class: PS\GestionBundle\EventListener\MyNotificationListListener
    my_admin_bundle.message_list_listener.class: PS\GestionBundle\EventListener\MyMessageListListener

services:
    my_admin_bundle.show_user_listener:
        class: %my_admin_bundle.show_user_listener.class%
        tags:
            - { name: kernel.event_listener, event: theme.navbar_user, method: onShowUser }
            - { name: kernel.event_listener, event: theme.sidebar_user, method: onShowUser }

    my_admin_bundle.menu_listener:
        class: %my_admin_bundle.menu_listener.class%
        tags:
            - { name: kernel.event_listener, event: theme.sidebar_setup_menu, method: onSetupMenu }
        arguments:
            - "@security.token_storage"
            - "@security.authorization_checker"

    my_admin_bundle.breadcrumb_listener:
        class: %my_admin_bundle.breadcrumb_listener.class%
        tags:
            - { name: kernel.event_listener, event: theme.breadcrumb, method: onSetupMenu }
        arguments:
            - "@security.token_storage"
            - "@security.authorization_checker"

    my_admin_bundle.task_list_listener:
        class: %my_admin_bundle.task_list_listener.class%
        tags:
            - { name: kernel.event_listener, event: theme.tasks, method: onListTasks }

    my_admin_bundle.notification_list_listener:
        class: %my_admin_bundle.notification_list_listener.class%
        tags:
            - { name: kernel.event_listener, event: theme.notifications, method: onListNotifications }

    #my_admin_bundle.message_list_listener:
    #    class: %my_admin_bundle.message_list_listener.class%
    #    tags:
    #        - { name: kernel.event_listener, event: theme.messages, method: onListMessages }

