admin_config_personne_index:
    path:     /
    defaults: { _controller: "UtilisateurBundle:Personne:index" }
    methods:  GET

admin_config_personne_show:
    path:     /{id}/show
    defaults: { _controller: "UtilisateurBundle:Personne:show" }
    methods:  GET

admin_config_personne_new:
    path:     /new
    defaults: { _controller: "UtilisateurBundle:Personne:new" }
    methods:  [GET, POST]

admin_config_personne_edit:
    path:     /{id}/edit
    defaults: { _controller: "UtilisateurBundle:Personne:edit" }
    methods:  [GET, POST]

admin_config_personne_delete:
    path:     /{id}/delete
    defaults: { _controller: "UtilisateurBundle:Personne:delete" }
    methods:  DELETE
