<?php

namespace PS\SpecialiteBundle\Repository;

/**
 * ChampSpecialiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampSpecialiteRepository extends \Doctrine\ORM\EntityRepository
{
}
