<?php

namespace PS\SpecialiteBundle\Repository;

/**
 * ChampStatistiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampStatistiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
