<?php

namespace PS\SpecialiteBundle\Repository;

/**
 * ChirugieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChirugieRepository extends \Doctrine\ORM\EntityRepository
{
}
