<?php

namespace PS\SpecialiteBundle\Repository;

/**
 * DonneeChampRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonneeChampRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $fiche
     * @param $etape
     * @return mixed
     */
    public function findByFicheEtape($fiche, $etape)
    {
        $em = $this->getEntityManager();

        $qb = $em->createQueryBuilder();
        $qb->select("c.aliasChamp, d.valeurChamp, c.id")
            ->from("PSSpecialiteBundle:DonneeChamp", 'd')
            ->join("d.champ", "c")
            ->where("d.fiche = :fiche")
            ->andWhere("c.etape = :etape")
            ->setParameter('fiche', $fiche)
            ->setParameter('etape', $etape);

        //$count = $qb->getSingleScalarResult();
        return $qb->getQuery()->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }

    /**
     * @param $fiche
     * @param $etape
     */
    public function deleteByFicheEtape($fiche, $etape)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->delete('PSSpecialiteBundle:DonneeChamp0', 'd');
        $qb->join("d.champ", "c")
            ->where("d.fiche = :fiche")
            ->andWhere("c.etape = :etape")
            ->setParameter('fiche', $fiche)
            ->setParameter('etape', $etape);

    }
}
