<?php

namespace PS\SpecialiteBundle\Repository;

/**
 * EtapeSpecialiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapeSpecialiteRepository extends \Doctrine\ORM\EntityRepository
{
}
