<?php

namespace PS\SpecialiteBundle\Repository;

/**
 * EtapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapeRepository extends \Doctrine\ORM\EntityRepository
{
    public function hasField($specialite, $etape)
    {
        $em = $this->getEntityManager();

        $qb = $em->createQueryBuilder();
        $qb->select("COUNT(c)")
            ->from("PSSpecialiteBundle:Champ", 'c')
            ->join("c.etape", "e")
            ->where("c.specialite = :specialite")
            ->andWhere("e.id = :etape")
            ->setParameter('specialite', $specialite)
            ->setParameter('etape', $etape);

        //$count = $qb->getSingleScalarResult();
        return $qb->getQuery()->getSingleScalarResult();
    }
}
