<?php

namespace PS\SpecialiteBundle\Repository;

/**
 * FicheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheRepository extends \Doctrine\ORM\EntityRepository
{
    public function details($fiche)
    {
        $em = $this->getEntityManager();

        $qb = $em->createQueryBuilder();
        $qb->select("c.aliasChamp, d.valeurChamp, c.libChamp, IDENTITY(c.etape) AS etape")
            ->from('PSSpecialiteBundle:Champ', 'c')
            ->leftJoin('PSSpecialiteBundle:DonneeChamp', 'd', 'WITH', 'c.id = d.champ AND d.fiche = :fiche')
            
            
            ->setParameter('fiche', $fiche);

        //dump($qb->getQuery()->getSQL());exit;

        //$count = $qb->getSingleScalarResult();
        return $qb->getQuery()->getResult();
    }
}
