<?php

namespace PS\SpecialiteBundle\Repository;

/**
 * HistoriqueFicheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueFicheRepository extends \Doctrine\ORM\EntityRepository
{
}
