<?php

namespace PS\SpecialiteBundle\Repository;

/**
 * ReferenceEtapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferenceEtapeRepository extends \Doctrine\ORM\EntityRepository
{
}
