<?php

namespace PS\SpecialiteBundle\Repository;

/**
 * TypeChampRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeChampRepository extends \Doctrine\ORM\EntityRepository
{
}
