<?php

namespace PS\SpecialiteBundle\Repository;

/**
 * ValidationGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValidationGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
