<?php

namespace PS\UtilisateurBundle\Repository;

/**
 * CompteAssocieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteAssocieRepository extends \Doctrine\ORM\EntityRepository
{
}
