<?php

namespace PS\UtilisateurBundle\Repository;

/**
 * InfoPersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoPersonneRepository extends \Doctrine\ORM\EntityRepository
{
}
