<?php

namespace PS\UtilisateurBundle\Repository;

/**
 * PersonneHopitalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneHopitalRepository extends \Doctrine\ORM\EntityRepository
{
}
