<?php

namespace PS\UtilisateurBundle\Repository;

/**
 * UtilisateurPreferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurPreferenceRepository extends \Doctrine\ORM\EntityRepository
{
}
