<?php

namespace PS\UtilisateurBundle\Repository;

/**
 * UtilisateurAssuranceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurAssuranceRepository extends \Doctrine\ORM\EntityRepository
{
}
